context:
  name: EditorConfig
  version: 0.17.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python ${{ python_min }}
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  python:
    imports:
      - editorconfig

about:
  homepage: http://editorconfig.org/
  summary: EditorConfig File Locator and Interpreter for Python
  license: BSD-2-Clause AND PSF-2.0
  license_file:
    - COPYING
    - LICENSE.BSD
    - LICENSE.PSF

extra:
  recipe-maintainers:
    - mitchellwood
    - ytausch
